services:
  - name: crypto-wallet
    type: web
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: SECRET_KEY_BASE
        sync: false
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: git-scm-db
          property: connectionString
  - name: redis
    type: redis
    inAllowList: []
    plan: free
    maxmemoryPolicy: noeviction

databases:
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-wallet-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: crypto-wallet-redis
          type: pserv
          property: hostport
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: crypto-wallet-db
    plan: starter
